config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'

  match 'questions/next/:last_q', to: 'questions#next', via: :get

  resources :questions do
    resources :answers, only: [:create, :update]
  end



  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  validates :description, presence: true, length: { minimum: 50 }
  validates :user_id, presence: true

  belongs_to :question
  belongs_to :user
end

app/models/question.rb
class Question < ActiveRecord::Base
  validates :title, presence: true, length: { minimum: 40, maximum: 255 }
  validates :description, presence: true, length: { minimum: 150 }
  validates :user_id, presence: true

  has_many :answers, dependent: :destroy
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :questions
  has_many :answers

  def self.from_omniauth(auth)
    User.where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate, only: [:create, :udpate]

  def create
    @question = Question.find(params[:question_id])
    @answer = Answer.new(answer_params)
    @answer.question_id = @question.id
    @answer.user_id = current_user.id
    if @answer.save
      redirect_to @question, notice: "Answer submitted!"
    else
      @answers = @question.answers
      render 'questions/show'
    end
  end

  def update
    @question = Question.find(params[:question_id])
    if current_user.id != @question.user.id
      redirect_to @question, alert: 'Only the asker of this question can decide the best answer!'
    end
    @answer = Answer.find(params[:id])
    if @answer.update_attributes(best: true)
      flash[:notice] = "Answer best-ed!"
    end
    redirect_to @question
  end

  private
  def answer_params
    params.require(:answer).permit(:description)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authenticate
    unless current_user
      redirect_to root_path, notice: "You must be signed in to do that!"
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate, only: [:new, :create, :edit, :udpate, :destroy]

  def index
    @questions = Question.all.order(created_at: :desc).limit(10)
  end

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers.order(best: :desc)
    @answer = Answer.new
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    @question.user_id = current_user.id
    if @question.save
      redirect_to @question, notice: 'New question submitted!'
    else
      render :new
    end
  end

  def edit
    @question = Question.find(params[:id])
    if current_user.id != @question.user.id
      redirect_to @question, alert: 'Only the asker of this question can edit it!'
    end
  end

  def update
    @question = Question.find(params[:id])
    redirect_to root_path if current_user.id != @question.user.id
    if @question.update_attributes(question_params)
      redirect_to @question, notice: "Question updated!"
    else
      render :edit
    end
  end

  def destroy
    @question = Question.find(params[:id])
    if current_user.id != @question.user.id
      redirect_to @question, alert: 'Only the asker of this question can delete it!'
    end
    @question.destroy
    redirect_to :questions, notice: "Question and all associated answers deleted!"
  end

  def next
    @questions = Question.all.order(created_at: :desc).offset(params[:last_q]).limit(5)
    render partial: 'next'
  end

  private
  def question_params
    params.require(:question).permit(:title, :description)
  end

  def answer_params
    params.require(:answer).permit(:description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url, notice: "Welcome back!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_markdown(text)
    markdown ||= Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, filter_html: true)
    markdown.render(text).html_safe
  end
end

app/views/layouts/_facebook.html.erb
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '331733057018577',
      xfbml      : true,
      version    : 'v2.2'
    });
  };

  (function(d, s, id){
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) {return;}
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/sdk.js";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
</script>

app/views/layouts/_header.html.erb
<header>


  <h1>Rescue Mission</h1>
  <p>
    <%= link_to 'New Question', new_question_path %> |
    <%= link_to 'Recent Questions', questions_path %> |
    <% if current_user %>
      Signed in as <strong><%= current_user.name %></strong> |
      <%= link_to "Sign out", signout_path, id: "sign_out" %>
    <% else %>
      <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
    <% end %>
  </p>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RescueMission</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/facebook' %>
  <%= render 'layouts/header' %>

  <% if flash.any? %>
    <div class="flash"><p><%= flash.notice %></p></div>
    <div class="flash"><p><%= flash.alert %></p></div> 
  <% end %>

  <div class="body-container">
    <%= yield %>
  </div>

</body>
</html>

app/views/questions/_next.html.erb
<% @questions.each do |question| %>
  <p class="question"><%= link_to question.title, question %> |
    Asked <%= time_ago_in_words(question.created_at) %> ago by <%= question.user.name %></p>
<% end %>

app/views/questions/edit.html.erb
<h1>Edit Question</h1>

<%= form_for @question do |f| %>

  <% if @question.errors.any? %>
  <h4>Question not saved, because:</h4>
    <% @question.errors.full_messages.each do |error| %>
    <ul>
      <li><%= error %></li>
    </ul>
    <% end %>
  <% end %>
  
  <div>
    <%= f.label :title, 'Title' %>
    <br>
    <%= f.text_field :title, size: "80" %>
  </div>

  <div>
    <%= f.label :description, 'Description' %>
    <br>
    <%= f.text_area :description, size: "80x10" %>
  </div>

  <%= f.submit %>
<% end  %>



<%= link_to "Delete this question", @question, method: :delete, data: { confirm: "Sure?" } %>

app/views/questions/index.html.erb
<h1 id="question-index-title">10 Most Recent Questions</h1>

<% @questions.each do |question| %>
  <p class="question"><%= link_to question.title, question %> |
    Asked <%= time_ago_in_words(question.created_at) %> ago by <%= question.user.name %></p>
<% end %>

<button id="next">Scroll Down to Load More Questions</button>

app/views/questions/new.html.erb
<h1>Ask a new question</h1>

<%= form_for @question do |f| %>
  <% if @question.errors.any? %>
  <h4>Question not saved, because:</h4>
    <% @question.errors.full_messages.each do |error| %>
    <ul>
      <li><%= error %></li>
    </ul>
    <% end %>
  <% end %>
  <div>
    <%= f.label :title, 'Title' %>
    <br>
    <%= f.text_field :title, size: "80" %>
  </div>

  <div>
    <%= f.label :description, 'Description' %>
    <br>
    <%= f.text_area :description, size: "80x10" %>
  </div>

  <%= f.submit %>
<% end  %>

app/views/questions/show.html.erb
<h2 class="question-title"><%= @question.title %></h2>

<div class="question-description">
  <%= render_markdown(@question.description) %>
  <p>
    <em>Asked <%= time_ago_in_words(@question.created_at) %> ago by <%= @question.user.name %></em>
  </p>
  <% if current_user && current_user.id == @question.user.id %>
    <%= link_to "Edit Question", edit_question_path(@question) %> |
    <%= link_to "Delete this question", @question, method: :delete, data: { confirm: "Delete the question. Final Answer?" } %>
    
  <% end %>
</div>

<% unless @answers.nil? %>
  <h2><%= pluralize(@answers.count, "Answer") %> </h2>

  <% @answers.each do |answer| %>
    <div class="answer<% if answer.best %> best<% end %>">
      <% if answer.best %>
        <p>*BEST ANSWER*</p>
      <% end %>
      <p>
        <%= render_markdown(answer.description) %>
      </p>
      <small>
        Answered <%= time_ago_in_words(answer.created_at) %> ago by <%= answer.user.name %>
      </small>

      <%= form_for [@question, answer] do |f| %>
        <%= f.hidden_field :best, value: true %>
        <%= f.submit "This is the best answer" %>
      <% end %>
    </div>
  <% end %>

<% else %>
  <h4>No answers yet!</h4>
<% end %>

<%= form_for [@question, @answer] do |f| %>
  <% if @answer.errors.any? %>
    <h4>Answer not saved, because:</h4>
    <ul>
      <% @answer.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.label :description, 'Answer this question:' %>
  <br>
  <%= f.text_area :description, size: "80x10" %>
  <br>
  <%= f.submit 'Save Answer' %>
<% end %>